### PR TITLE
Adding live information

### PR DESCRIPTION
**Pull request by patrickstorm**
## Overview
I wanted to stop having to check Poloniex and the poloLender to see how my loans were doing. Decided to add some basic info to the live page.

screen shot 2017-06-19 at 6 42 45 pm

### CODE REVIEW

**Comment by denravonska** [comment]
Yes! I thought it was supposed to show this but there was some problem on my end.

**Review by dutu — CHANGES_REQUESTED** [review]
would you please add the CSS style changed under the directory public/stylesheets, rather than modifying the webix.css file (since webix.css will be overwrite when upgrading to a new webix release?

**Comment by patrickstorm** [comment]
Absolutely, I can get to it sometime today.

**Comment by patrickstorm** [comment]
After using this for a couple of days, I found that the "Open Orders" section isn't working. I should have some time today to get that working.

I would also like to add a section in for profit, average interest rate by currency, etc.

**Comment by dutu** [comment]
Could you create the PR towards the dev branch until it's tested and ready?

**Comment by dutu** [comment]
@patricktoerner if you submit a PR towards the `dev` branch I can merge and help fixing the updates

**Comment by denravonska** [comment]
@dutu You can change the target branch by editing the PR.

**Comment by xR2** [comment]
This looks really nice, how can I test it locally?

**Comment by dutu** [comment]
@patricktoerner i included live tab in the version 0.11.0. Will get the market cap widget, it looks nice

**Pull request closed without merging**
